menu:
    Blog: /
    Archive: /archives/
    About: /about.html
    GitHub: https://github.com/jeremyhe-cn
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png
logotext: <font color=gray size="7">{</font><font size=7> AL </font><font color=gray size=7>}</font>

# Comment
# e.g disqus: seansun
disqus:
duoshuo: j-cn


# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
