menu:
    Index: /
    Archive: /archives/
    About: /about.html
    GitHub: https://github.com/jeremyhe-cn
    Rss: /atom.xml

# pilgi字体
favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: 
duoshuo:
cloudTie: 1bc56f9599fa479a890196981ff9f0b4

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
